export const categories = [
  {
    id: 1,
    name: "Pizza",
    image: require("../assets/images/pizzaIcon.png"),
  },

  {
    id: 2,
    name: "Burger",
    image: require("../assets/images/pizzaIcon.png"),
  },
  {
    id: 3,
    name: "Italian",
    image: require("../assets/images/pizzaIcon.png"),
  },
  {
    id: 4,
    name: "Chinese",
    image: require("../assets/images/pizzaIcon.png"),
  },
  {
    id: 5,
    name: "Noodles",
    image: require("../assets/images/pizzaIcon.png"),
  },
  {
    id: 6,
    name: "Sweets",
    image: require("../assets/images/pizzaIcon.png"),
  },
];

export const featured = {
  id: 1,
  title: "Hot and Spicy",
  description: "soft and tender fried chicken",
  restaurants: [
    {
      id: 1,
      name: "Papa Jones",
      image: require("../assets/restaurants/restaurant.jpg"),
      description: "Hot and Spicy",
      lng: 38.215602,
      lat: -85.5324269,
      address: "434 second stress",
      stars: 4,
      reviews: "4.4k",
      category: "Fast Food",
      dishes: [
        {
          id: 1,
          name: "Pizza",
          description: "cheezy garlic pizza",
          price: 10,
          image: require("../assets/dishes/pizzaDish.jpeg"),
        },
        {
          id: 2,
          name: "Pizza",
          description: "cheezy garlic pizza",
          price: 15,
          image: require("../assets/dishes/pizzaDish.jpeg"),
        },
        {
          id: 3,
          name: "Pizza",
          description: "cheezy garlic pizza",
          price: 10,
          image: require("../assets/dishes/pizzaDish.jpeg"),
        },
        {
          id: 4,
          name: "Pizza",
          description: "cheezy garlic pizza",
          price: 10,
          image: require("../assets/dishes/pizzaDish.jpeg"),
        },
        {
          id: 5,
          name: "Pizza",
          description: "cheezy garlic pizza",
          price: 10,
          image: require("../assets/dishes/pizzaDish.jpeg"),
        },
      ],
    },

    {
      id: 1,
      name: "Papa Jones",
      image: require("../assets/restaurants/restaurant.jpg"),
      description: "Hot and Spicy",
      lng: 38.215602,
      lat: -85.5324269,
      address: "434 second stress",
      stars: 4,
      reviews: "4.4k",
      category: "Fast Food",
      dishes: [
        {
          id: 1,
          name: "Pizza",
          description: "cheezy garlic pizza",
          price: 10,
          image: require("../assets/images/pizzaIcon.png"),
        },
        {
          id: 2,
          name: "Pizza",
          description: "cheezy garlic pizza",
          price: 10,
          image: require("../assets/images/pizzaIcon.png"),
        },
        {
          id: 3,
          name: "Pizza",
          description: "cheezy garlic pizza",
          price: 10,
          image: require("../assets/images/pizzaIcon.png"),
        },
        {
          id: 4,
          name: "Pizza",
          description: "cheezy garlic pizza",
          price: 10,
          image: require("../assets/images/pizzaIcon.png"),
        },
        {
          id: 5,
          name: "Pizza",
          description: "cheezy garlic pizza",
          price: 10,
          image: require("../assets/images/pizzaIcon.png"),
        },
      ],
    },
    {
      id: 1,
      name: "Papa Jones",
      image: require("../assets/restaurants/restaurant.jpg"),
      description: "Hot and Spicy",
      lng: 38.215602,
      lat: -85.5324269,
      address: "434 second stress",
      stars: 4,
      reviews: "4.4k",
      category: "Fast Food",
      dishes: [
        {
          id: 1,
          name: "Pizza",
          description: "cheezy garlic pizza",
          price: 10,
          image: require("../assets/images/pizzaIcon.png"),
        },
        {
          id: 2,
          name: "Pizza",
          description: "cheezy garlic pizza",
          price: 10,
          image: require("../assets/images/pizzaIcon.png"),
        },
        {
          id: 3,
          name: "Pizza",
          description: "cheezy garlic pizza",
          price: 10,
          image: require("../assets/images/pizzaIcon.png"),
        },
        {
          id: 4,
          name: "Pizza",
          description: "cheezy garlic pizza",
          price: 10,
          image: require("../assets/images/pizzaIcon.png"),
        },
        {
          id: 5,
          name: "Pizza",
          description: "cheezy garlic pizza",
          price: 10,
          image: require("../assets/images/pizzaIcon.png"),
        },
      ],
    },
  ],
};
